# Generated by Django 5.0.1 on 2024-02-02 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employnumber', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=70)),
                ('date_of_entry', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
